### ISSUE TITLE
Título y resumen

### ISSUE THREAD

**Issue by memaldi** [Betagmr/UD-TFM#1]
Hola Asier,

No sabía cómo ponerte comentarios en el build, así que los pongo aquí. Realmente sólo tengo un comentario:

`En un mundo empresarial cada vez más dinámico y competitivo, el uso de metodologías 
y estándares modernos [...]` -> Estándares y metodologías, ¿para qué (desarrollo, despliegue...)?

¿Has podido pensar un título?

Un saludo.

**Comment by Betagmr** [comment]
Buenas Mikel,

Los estándares y metodologías cubren tres frases diferentes del desarrollo:
- **Crear la base de los proyectos** (Configuración de herramientas, estructura del código, gestión de datasets...)
- **Desarrollo del proyecto** (Almacenamiento de modelos, gestión de las métricas, versionado, uso de la infraestructura)
- **Finalización del proyecto** (Reutilización de código, documentación de proyectos...)

El despliegue podría entrar dentro de la fase de `desarrollo del proyecto` y como tal la infraestructura esta preparada para hacerlo, pero no lo vamos a abordar en el TFM porque seria demasiado extenso.

He ido pensando en títulos y aunque no tengo todavía uno definitivo te dejo algunos, igual se puede hacer alguna mezcla de conceptos:
1. Implementación de un estándar basado en el Diseño Atómico dentro de Proyectos de IA y ML
2. Introduciendo el diseño atómico en el desarrollo de modelos de IA
3. Diseño de un Marco Tecnológico para la Adopción de Prácticas Modernas en Proyectos de IA y ML
4. Adopción de las nuevas tendencias dentro del desarrollo de modelos de IA
5. Diseño e Implementación de un STACK tecnológico dentro del ciclo de vida ágil del modelo (MLOPs)

**Comment by memaldi** [comment]
Hola Asier,

Sí, me refería a que la frase parecía como inconclusa. Podría ser algo así como "un mundo empresarial cada vez más dinámico y competitivo, el uso de metodologías y estándares modernos para el desarrollo de proyectos software".

Sobre los títulos, creo que el 1 y el 3 pueden ser los más representativos. En el título, evita el uso de las mayúsculas, el uso de abreviaturas, y el uso de palabras en inglés.

Un saludo.

**Comment by Betagmr** [comment]
Diseño e implementación de un marco tecnológico para la adopción de prácticas modernas en proyectos de inteligencia artificial
